Controllers/CustomerOrderController.cs
using CrystalDecisions.CrystalReports.Engine;
using finalmvcfirst.Data_folder;
using finalmvcfirst.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace finalmvcfirst.Controllers
{
    public class CustomerOrderController : Controller
    {
        // GET: CustomerOrder
        private ApplicationDbContext db = new ApplicationDbContext();
        List<Customer> mst = new List<Customer>();
        List<Order> sdt = new List<Order>();
        public ActionResult Index(string CustomerID = "")
        {
            CustomerOrder a = null;
            if(CustomerID !="") //Edit
            {
                sdt = (from d in db.Orders where d.CustomerID == CustomerID select d).ToList();
                Customer m = db.Customers.Find(CustomerID);
                a = new CustomerOrder { CustomerID = m.CustomerID};
                
            }
            ViewBag.Records = sdt;
            TempData["sdt"] = sdt;
            return View(a);
        }
        public void AddLine(CustomerOrder d)
        {
            sdt = TempData["sdt"] as List<Order>;
            if (sdt == null)
                sdt = new List<Order>();
            sdt.Add(new Order() { OrderID = d.OrderID, orderDate = d.orderDate, OrderStatus = d.OrderStatus });
            
            ViewBag.records = sdt;
            TempData["sdt"] = sdt;
        }
        public void SaveMe(CustomerOrder m2)
        {
            DeleteMe(m2.CustomerID);
            Customer md = new Customer() { CustomerID = m2.CustomerID, CutomerName = m2.CutomerName, BillingAddress = m2.BillingAddress, ShippingAddress = m2.ShippingAddress, };
            db.Customers.Add(md);
            db.SaveChanges();
            sdt = TempData["sdt"] as List<Order>;
            foreach (Order d in sdt)
            {
                Order r = new Order() { OrderID = d.OrderID,CustomerID=m2.CustomerID, orderDate = d.orderDate, OrderStatus = d.OrderStatus };
                db.Orders.Add(r);
                db.SaveChanges();
            }

            TempData["sdt"] = "";
            Session["sdt"] = "";

        }
        public void DeleteMe(string CustomerID)
        {
            db.Database.ExecuteSqlCommand($"delete Orders where CustomerID='{CustomerID}'");
            db.Database.ExecuteSqlCommand($"delete Customers where CustomerId='{CustomerID}'");
            db.SaveChanges();
        }
        [HttpPost]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult index(CustomerOrder m2, string ButtonType)    
        {
            if (ButtonType == "Add")
            {
                AddLine(m2);
                return PartialView("_PartialPage1");
            }
            else if (ButtonType == "Save")
                SaveMe(m2);
            else
                DeleteMe(m2.CustomerID);
            return Json(new { url = Url.Action("list") });
        }
        [Route("Main")]
        public ActionResult List()
        {
            TempData["sdt"] = "";
            List<CustomerOrder> c = new List<CustomerOrder>();
            var a = db.Customers.ToList();
            foreach (var m2 in a)
            {
                c.Add(new CustomerOrder { CustomerID = m2.CustomerID, CutomerName = m2.CutomerName, BillingAddress = m2.BillingAddress, ShippingAddress = m2.ShippingAddress,  });
            }
            return View(c);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Customer Order", "Index", "CustomerOrder")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
</body>
</html>

Views/Shared/_PartialPage1.cshtml
@if (@ViewBag.records != null)
{
    <table class="table">
        <tr>
            <th>
                OrderID
            </th>
            <th>
                orderDate
            </th>
            <th>
                OrderStatus
            </th>
            

        </tr>
        @foreach (var item in @ViewBag.records)
        {

            <tr>
                <td>
                    <input type="text" id="OrderID" name="OrderID" value="@item.OrderID" class="form-control" />
                </td>
                <td>
                    <input type="text" id="orderDate" name="orderDate" value="@item.orderDate" class="form-control" />
                </td>
                <td>
                    <input type="text" id="OrderStatus" name="OrderStatus" value="@item.OrderStatus" class="form-control" />
                </td>
                
            </tr>
        }
    </table>
}